### PR TITLE
Tiernan dev

### PR DESCRIPTION
**Pull request by tiernanbyrne**
Adding monthly graph

### CODE REVIEW

**Review by xX-Michael-Robertson-Xx — APPROVED** [review]
You could use the US flag emoji in the team bios... but it's a minor detail.

**Review by cool-and-normal — CHANGES_REQUESTED** [review]
Fix image

**Review by xX-Michael-Robertson-Xx — APPROVED** [review]
Fixed?

**Review by cool-and-normal — APPROVED** [review]
Nice, looks good.

**Pull request merged**
